---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden
  namespace: default
data:
  DOMAIN: https://vault.${SECRET_DOMAIN}
  SIGNUPS_ALLOWED: "false"
  SMTP_FROM: info@${SECRET_DOMAIN}
  SMTP_FROM_NAME: Vaultwarden
  SMTP_SECURITY: "starttls"
  WEBSOCKET_ENABLED: "true"