---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app mastodon
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  values:
    controllers:
      main:
        type: deployment
        labels:
          pvcAffinity: mastodon
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: tootsuite/mastodon
              tag: v4.2.3
            command: ['bash', '-c', 'rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000']
            envFrom:
              - configMapRef:
                  name: mastodon
              - secretRef:
                  name: mastodon-app-secret
              - secretRef:
                  name: mastodon-db-secret
        pod:
          securityContext:
            fsGroup: 991
            fsGroupChangePolicy: OnRootMismatch
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - key: pvcAffinity
                        operator: In
                        values:
                        - mastodon
                    topologyKey: kubernetes.io/os
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    service:
      main:
        ports:
          http:
            port: &port 3000