---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app authentik-redis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            nameOverride: *app
            image:
              repository: redis
              tag: 7.2.4
            command:
              - sh
            args:
              - -c
              - >-
                redis-server --requirepass $REDIS_PASSWORD
            env:
              REDIS_PORT: &port 6379
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: authentik-redis-secret
                    key: AUTHENTIK_REDIS__PASSWORD
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 256M
    service:
      main:
        controller: main
        ports:
          http:
            protocol: TCP
            port: *port