---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mastodon-db
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            nameOverride: *app
            image:
              repository: postgres
              tag: 16
            env:
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    key: DB_USER
                    name: mastodon-db-secret
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: DB_PASS
                    name: mastodon-db-secret
    service:
      main:
        ports:
          http:
            protocol: TCP
            port: &port 5432
    persistence:
      data:
        enabled: true
        storageClass: ceph-rbd
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /var/lib/postgresql/data
            subPath: postgres