apiVersion: v1
kind: Secret
metadata:
    name: mastodon-db-secret
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:B21qm/0WsfE=,iv:H8TYcOtNrttaxHC8ir/bHXOsFJvO2HJoOnOZ3QlnSws=,tag:wGsuMaA3TWVSet3ED9phlw==,type:str]
    DB_PASS: ENC[AES256_GCM,data:RIxFODpCDWFEuL3JLDI=,iv:w/doOLBxzJQm6nOIF1cJJhVPIbHTOk+CZy7He5CGXyo=,tag:DqF6zr8GlFS/ss5Ow4Bd7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxnpvut5ja8ghkn9gcs0sqenh2nlk2puqqtnzm8wv2md9w5jhp4sarsr8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT0JZM0R4UjllNVN0NkZv
            Zi9QbVk5Mmp3Q1RVSjI0dm5HazJsWWhGY3dVCjR0Q1E1blpWclVudFZ0WEY1VmNH
            QlA0TnVsSm95TGRzQ3FLVXNlOEI1TGMKLS0tIHFrU2hHaU1rd0oybXFrYzhrUmo4
            R1ZYMkc4WlQ5RGtGMHZsTktndWEvS3cKTRYiH/FK6/iKSzhEtwmJZ+k+xzJlz/w7
            RXJHT3/Kqhd/5Ejy7Uvz9xYoYX/722/jenSXd+asQ+j9gPsOsz0dGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T12:35:15Z"
    mac: ENC[AES256_GCM,data:AqV5QjUKS+JVx9tZi0l5d0Mq3R5KLzJvPVCQleA16L64jAjh95SIdipqiqRLrf4sej3x+kmuleJbvrYClV9e41/QPOuieAPgH55lYpkIBwAtI3rIuw1qAHzvi8dgWl/7nAmn9HpnRxNEat9jilKJClnvlWopE/dOxOQIpHPgHHo=,iv:/20wj13prUvFIEbwXXYqh5TT9mxoSYwkbpmNutRHc3g=,tag:9zqHUhIKSZirs5KzPQBhOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
