---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.2.3
            env:
              TZ: ${TIMEZONE}
              HOST_WHITELIST_ENTRIES: &host "{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
        pod:
          securityContext:
            runAsUser: ${CONFIG_APP_UID}
            runAsGroup: &gid ${CONFIG_MEDIA_UID}
            fsGroup: *gid
            fsGroupChangePolicy: OnRootMismatch
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 5M
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080
    persistence:
      config:
        enabled: true
        existingClaim: *app
      media:
        enabled: true
        existingClaim: media