---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media
provisioner: nfs.csi.k8s.io
parameters:
  server: vlan88.nas.hdc
  share: /mnt/main/media
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
