---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app minio-external
spec:
  ingressClassName: internal
  rules:
  - host: &app_host minio.${SECRET_DOMAIN_INTERNAL}
    http:
      paths:
      - backend:
          service:
            name: minio-external
            port:
              number: 9002
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - *app_host
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &mastodon minio-external-mastodon
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/rewrite-target: /mastodon/$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Content-Type-Options nosniff;
      add_header Content-Security-Policy "default-src 'none'; form-action 'none';" always;
spec:
  ingressClassName: external
  rules:
  - host: &mastodon_host mastodon-static.${SECRET_DOMAIN}
    http:
      paths:
      - backend:
          service:
            name: minio-external
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /(.*)
  tls:
  - hosts:
    - *mastodon_host
