---
apiVersion: v1
kind: Service
metadata:
  name: minio-external
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9002
    protocol: TCP
  sessionAffinity: None
  type: ClusterIP
