---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app bluebubbles
spec:
  ingressClassName: internal
  rules:
  - host: &host bluebubbles.${SECRET_DOMAIN_INTERNAL}
    http:
      paths:
      - backend:
          service:
            name: *app
            port:
              number: 51234
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - *host
