---
apiVersion: v1
kind: Service
metadata:
  name: bluebubbles
  annotations:
    io.cilium/lb-ipam-ips: "10.8.8.123"
spec:
  ports:
  - name: http
    port: 51234
    protocol: TCP
    targetPort: 51234
  type: LoadBalancer
