---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jmac-ph-ghost
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghost
              tag: 5.74.0
            env:
              database__client: mysql
              url: https://${SECRET_DOMAIN_INTERNAL}
            envFrom:
              - secretRef:
                  name: jmac-ph-ghost-secret
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "${SECRET_DOMAIN_INTERNAL}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    service:
      main:
        ports:
          http:
            port: &port 2368
    persistence:
      config:
        enabled: true
        storageClass: ceph-rbd
        globalMounts:
          - path: /var/lib/ghost/content