apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:X34/nAQT6D2rVYX2A1WW33KRIapknGSBbkxzpjhkLmriz5EcXGRMag==,iv:mZ+BqZNy5COeeQdQcnLCKV7YyhTSXCOjo5LBfvrEDvQ=,tag:iyvqIUG4xt/eAwKMnXVj5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxnpvut5ja8ghkn9gcs0sqenh2nlk2puqqtnzm8wv2md9w5jhp4sarsr8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVGw4MTN2SmY2alNRdUdi
            blBDRjFLaGxUbk9HZEJEbUoxMFVXeG9UQkVvClh6YkdhNmNiWUgwWHBnb2NRQkE0
            eFBHUFlvOVJJTWphVWFuZ3FpaEQvQ2sKLS0tIFFLcUZDZDAyRVhrRFBqNUxYcXZm
            L0QyQ0gxQVBsOWtNLzJXZWNJUGEwYWcKE0LlSbF5m9zxwWCB01zyfBokFTAF0ujg
            ej0RBQJErz20dUWtwwn2NkF0OssN3wEVReNmuW0dhxK4VKC2W9fUww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T16:25:42Z"
    mac: ENC[AES256_GCM,data:mrcTsbSTjrH2AO/UZP1/8U0tcOPpBSjq9AFwL/G/DJNU+KUa4nfMrVMTiiLMMOxNKF5Dyc+bkbFgRCv90Ddu+Q8Qd+U6SPQgJSkk19c+CuhvnRrkIxfw1vnFoWzccT8SP1y6xIEgVFjJGDa/dbjthi2Faq3MeR1osw1bfgwr3AY=,iv:Yqfm+1R/AxiDliHIAJQaiBrYAKVx6GuY0qbUBXDB0vU=,tag:PZraskOzrHhEr/mHmT39xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
