---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app prometheus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: 25.12.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    alertmanager:
      enabled: false
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-pushgateway:
      enabled: false
    server:
      global:
        scrape_interval: 10s
        scrape_timeout: 10s
        evaluation_interval: 10s
      remoteWrite:
        - url: "http://influxdb.monitoring:8086/api/v1/prom/write?db=prometheus"
      remoteRead:
        - url: "http://influxdb.monitoring:8086/api/v1/prom/read?db=prometheus"
      persistentVolume:
        enabled: false
    serverFiles:
      prometheus.yml:
        scrape_configs:
          # - job_name: mikrotik
          #   static_configs:
          #   - targets: ['mikrotik-exporter:9436']
          - job_name: mktxp
            static_configs:
            - targets: ['mktxp:49090']
          - job_name: blackbox
            metrics_path: /probe
            params:
              module: [icmp_ipv4]
            scrape_interval: 10s
            static_configs:
              - targets:
                - ${SECRET_ISP1_GW}
                - ${SECRET_ISP2_GW}
                - 1.1.1.1
                - 1.0.0.1
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: blackbox-exporter.monitoring:9115
          - job_name: blackbox-http
            metrics_path: /probe
            params:
              module: [http_2xx]
            scrape_interval: 10s
            static_configs:
              - targets:
                - ${SECRET_CPE1_TARGET}
                - ${SECRET_CPE2_TARGET}
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: blackbox-exporter.monitoring:9115