apiVersion: v1
kind: Secret
metadata:
    name: vpn-unlimited-ro-wg-secret
    namespace: vpn
type: Opaque
stringData:
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:SkDS4RBmUWvcD/0mGQ==,iv:XJ2KjhHNBCOgEdXA0P+w5FiUGII+buGHtXslKrpZdPA=,tag:0r/9vKqafdtXjrtAr6VvQw==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:8bqB,iv:c54JrUvqkZKjJpIjleXzr0DX34Can67/2N1XgrLV8tw=,tag:SOyDM6+PxOViC7WjhTrh3g==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:MiOZvSspXfQSkdoOB7TyaV9uVyEakmI6wU1QOL5YWbB3onWxwG+xd03goAU=,iv:hgZLEqh7YYs2xffuoBfmaL5jnJnEtKHMVY0hUx+WZnY=,tag:xrrQi0IVukqJ8HHWidEt3Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:p64jaQMe4b07kdj3ZA80tDZlYpKAiHq3G1vpiaRy8y4fftE55hAwLcT3+qw=,iv:czb6JyD1lu4Ssy4T5RNvyfRyxd9fmRZ/13sH9WxFk48=,tag:iApDsDuf6VDslaJsoZoAOA==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:K+p+WDVn+BqGhKJQT84lG9PMv7b5zqtKzplmTc4gYAedLDg/x+z8kDhyU4Q=,iv:bJbdDOQaP5IEWYBZOBNmFdPkDEB1pwFAUAp9fjTdY+E=,tag:/MqGfO3/uBOu8OUm7OroEA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:vS950FLkZOeXl96McVso,iv:g2AE1JE75s5kLYtmV7ZoCaBEc7QAMrmp5ZSWWEoTY+c=,tag:jNcjO89ehUp4T5oUPGouxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxnpvut5ja8ghkn9gcs0sqenh2nlk2puqqtnzm8wv2md9w5jhp4sarsr8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ3ZCbFhHTW9nNVVLWUlz
            SVYwdHJydTV5LzB5YlJSbWtqZHJ5UnM3UGhRClloZ3I4SkpXdkxKOGJNMVFQWnBE
            TFFJZ1NNZk5CVlZUeHlXRGFkZ2Z4Y3cKLS0tIHRxZFhvWGhoNnE1WHN3bUxobmg1
            Vm02dVZ6Mi9aUnhlVk9za1dER2F3L0EKDmh0JIunFvwAjhH9Ey7qZFTWgsO1GaJf
            ATonqqHvDBH9BREDjv3GXwNG7NVZCFTsB2rNU+dRD0HImXTx9LO35g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-25T10:37:33Z"
    mac: ENC[AES256_GCM,data:YjC9IoJbGkRitr+LIdxD3Tfj5M71jPtIG7GRMqOsNCQLns4F7Mg/puzb3+31JmIwKSijoolcL5YV+185I2KgzvOxY8ZJyX1/AbT6nw22OlvHTZKOjB0xrnMyPl3hsoIqA8Z9q65AgtpxCWoq7sVjzhn1riJhlUGb+DTrl/Gk3n8=,iv:JNAhE0YS4dkokxuulHIeWaT59lYEc0wCvlOCNfSlamc=,tag:b+K3KDlYx4M7SHF5i93jpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
