---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
subsets:
- addresses:
  - ip: ${SECRET_PROXMOX_IP}
  ports:
  - name: https
    port: 8006
    protocol: TCP
  - name: websocket
    port: 5900
    protocol: TCP
  - name: spice
    port: 3128
    protocol: TCP
