---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8006
  sessionAffinity: None
  type: ClusterIP
