---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nut-exporter-home-office
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: boardyuk/nut-influxdb-exporter
              tag: latest # has no other tag, heh
            env:
              HOSTNAME: &upsname home-office
              INFLUXDB_DATABASE: nutups
              INFLUXDB_HOST: influxdb.monitoring
              INFLUXDB_PORT: "8086"
              NUT_HOST: ${SECRET_HOME_OFFICE_NUT_IP}
              NUT_PORT: "3493"
              UPS_NAME: *upsname
              WATTS: "900"
              INTERVAL: "15"
            envFrom:
              - secretRef:
                  name: nut-exporter-home-office-secret
    service:
      main:
        controller: main
        enabled: false