---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app omada-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: mbentley/omada-controller
              tag: 5.13
            env:
              MANAGE_HTTPS_PORT: 443
        pod:
          securityContext:
            sysctls:
              - name: net.ipv4.ip_unprivileged_port_start
                value: "0"
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        hosts:
          - host: &host "omada.${SECRET_DOMAIN_SECONDARY}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "10.8.8.121"
        ports:
          http:
            enabled: true
            protocol: HTTPS
            port: 443
            targetPort: 443
          omada-tcp1:
            enabled: true
            protocol: TCP
            port: 29811
            targetPort: 29811
          omada-tcp2:
            enabled: true
            protocol: TCP
            port: 29812
            targetPort: 29812
          omada-tcp3:
            enabled: true
            protocol: TCP
            port: 29813
            targetPort: 29813
          omada-tcp4:
            enabled: true
            protocol: TCP
            port: 29814
            targetPort: 29814
          omada-udp1:
            enabled: true
            protocol: UDP
            port: 29810
            targetPort: 29810
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /opt/tplink/EAPController/data