---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_INTERNAL/./-}-staging"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN_INTERNAL/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_INTERNAL}"
  dnsNames:
    - "${SECRET_DOMAIN_INTERNAL}"
    - "*.${SECRET_DOMAIN_INTERNAL}"
