apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:aPkEmFn12w==,iv:jlahmIIspBjUKJ52E/RvGI3Nc3gzECwRp6cokswyZu4=,tag:JccRMQN7CGpsoi95+s7gdQ==,type:str]
    SECRET_NEXTCLOUD_IP: ENC[AES256_GCM,data:CIUytClF/CqD,iv:Yakhb+uXWeHhS5xiI3FdGuOzQulP9KLLH4u2NPsjX8Q=,tag:KaOy7h418JutjBaBzEOypw==,type:str]
    SECRET_JELLYFIN_IP: ENC[AES256_GCM,data:fptbOLIvod6p,iv:tUb6K2Bkp3q1qKKEQR7kC7W3605+SI+C7kBdK9ByXMo=,tag:5O17uQ5aaib6LWX3pau4xg==,type:str]
    SECRET_CCTV_IP: ENC[AES256_GCM,data:DWbKzD9nc22V,iv:f5O+Xa4zM36bljSjdeAA/zpdjSiJlMb4CMg32lAPvnU=,tag:L3p9qaL4vPbcqqtDufv6Rw==,type:str]
    SECRET_HOME_ASSISTANT_IP: ENC[AES256_GCM,data:s2Kg6m0WCCS+JQf1IQ==,iv:V5t9KBTg6g9i0GBojQJt32xG9ElJPi8G8vi151ZEims=,tag:JMcp7wXu9JB/SJSbngHTjQ==,type:str]
    SECRET_SANED_HOSTS: ENC[AES256_GCM,data:ARzWoS1IDTybcB+kVfs=,iv:BARS1wst4uCG2q5VZQdRAcU55Kn0wZMk+k0PnCCBdWk=,tag:P1URGNsDEoFaEpSlzIfWzQ==,type:str]
    SECRET_NAS_HOST: ENC[AES256_GCM,data:5HHw8Qyclz6p0ebUuN8=,iv:jtVF0YcFZ6btzzAus0dR64OgpApSCD6pr1D5a2noxhU=,tag:Hk3mqsR3YAEnpsM4tgvrog==,type:str]
    SECRET_NAS_IP: ENC[AES256_GCM,data:hTGR2rzDWfyt,iv:tlRFlCItKsczOzmpXIGwSRDs2DQslzNjZOcUaStlV2s=,tag:/36N5UWW/3d7Y6bD4BKq1A==,type:str]
    SECRET_ISP1_GW: ENC[AES256_GCM,data:fWaQgbety2MZwOaChA==,iv:hSQcGAjEMOwtxIHTCTXVs5uMMVDK+bm5YvcQYvw7A/Y=,tag:wuv4bATndyGnBxs7vi8i1g==,type:str]
    SECRET_ISP2_GW: ENC[AES256_GCM,data:yF/s/wjnYiiuBIDNEg==,iv:wrx939HKrsA5PQkr8EaMeYvs7zQwkLj7lQfj6eMXbXk=,tag:N3ShJndFVq6MIjKbAFAd9g==,type:str]
    SECRET_CPE1_TARGET: ENC[AES256_GCM,data:zXnph4vJrGwdxguyd0lmZTFcO9uJ/HSM5JMfBCU6z6DXhFXXQ6p1xABFeWbbhOhTfC8=,iv:9AgAK7g3GZtyCksfcLm+6iQDbTqWL4AmQGBEwL+uIdU=,tag:Y4l46VuGBZUAr8WQq6QjjA==,type:str]
    SECRET_CPE2_TARGET: ENC[AES256_GCM,data:qxFhxVprOpRcMef7O5s5tQCXdzokB7tStzBYEQdGMlRh6zwmQgshOWoBthj7qh068TE=,iv:WiIpjSrgAxa/87hcCtuY7JItqFrEc0FmbWbEXyP/hYw=,tag:GNpjBGHSpzSknWJ+FL0I5g==,type:str]
    SECRET_HOME_OFFICE_NUT_IP: ENC[AES256_GCM,data:7J/gAnNJXkIxuLjrHYw=,iv:EI6flDSMxufTqMxYKi1IBITTJaJczy9qJZcX1Zig8U0=,tag:SYz6SUqwHMI1U33QITBpTg==,type:str]
    SECRET_UPS1_NUT_IP: ENC[AES256_GCM,data:ek866YEVl9Lx,iv:r+HvSUVRwlWOuZPz4gsDN0WFrLfauoEJ3RexROzDBL0=,tag:vbtoBezhuMrT0S5GMIAXSg==,type:str]
    SECRET_ROUTER_LOCAL_IP: ENC[AES256_GCM,data:LuR0mbPlaVU=,iv:dplbaZ2UDrq8IT7DKRv/ZeOZV8m4GIyYHJKgITd/zwk=,tag:gGBD37xt3i7ZCm0qvvRG6Q==,type:str]
    SECRET_MKTXP_USERNAME: ENC[AES256_GCM,data:CGsCA6NfIhISfQ==,iv:0h6IDpuyrO0KUaSnl/QECBp2SW5eZ4Q2mieh5uFchOo=,tag:qjauC/qjOzQQtHGOMC8WtQ==,type:str]
    SECRET_MKTXP_PASSWORD: ENC[AES256_GCM,data:8K8fNYHOVOIu4BBbKFI=,iv:969gEhzfinM/hrP2SI6oX7YDdWr7XUAtNdYZ0rHgcqg=,tag:wKhnUXcWnP3Qbf9cqz/VlQ==,type:str]
    SECRET_VOIP_IP: ENC[AES256_GCM,data:4Q6C2ny8hWYRNXZd,iv:5G0fe9bXzTf+5yuz3hogLJoYJaYgQzpLmxzDWzcs91o=,tag:cIbSvBAyLiSNg9IDfUZCkQ==,type:str]
    SECRET_PROXMOX_IP: ENC[AES256_GCM,data:Okuo/kMJQg/V,iv:SpGR76IQTCYO3vvuLkm0DAzAArJ0QXVM8Rg2DOB45Ng=,tag:U3D8/XBdguW3rA7ZFUSdkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxnpvut5ja8ghkn9gcs0sqenh2nlk2puqqtnzm8wv2md9w5jhp4sarsr8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTlBmSUhERlNjZjFQdHFG
            S3d6c2JKMlZ5b24yNFN5RnhTdmUybUVzZm00CmJUOU5lYUJwS0RSYTlwbDFrMUdj
            dzZ0UE5LOWsvVk1UVFFLd0ptV21nbFkKLS0tIC9nRVcvVlBvWm5yQlBGQWwvRG5B
            VGtZZ1pCeDFxNlo0UzIyTlhXc0ZvY0EKBqiW6z7wy+2Mjsk5m6/469XCremShVd6
            YjKBkzI2sE+Zi2hwtT97K0uGO35qI05JQ+KDIT6Sx10L+z1rdast+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-18T15:31:12Z"
    mac: ENC[AES256_GCM,data:WqPzrC/BCd01k5OMr8367GPttlRWheEqaoop4M0RytHfcDTckH7/5O2EekFPuGM0RfxsZG1tgUpgs8XNRPvZnPVlFim0QRiMME1P4Z8zhWRZqwCzUXScSr7kljfhRF1NdSzYMRIVAnSe+KF4vW/u5ZruYJ3QFHJnTfGhI1KHDO8=,iv:AOrB0HdzAZ7js166a8BcAawQ8WR9IWzFpA0HYD4yYRU=,tag:BcWXhRep2rXH9Y7/mu9tGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
