apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Hhu+waUz6EKDtBKF,iv:bsOKoX7J56XiFfPwhcvYjFXppMS75VpDj2O7T0rECvk=,tag:hiZKndw/mAHph4hSm12sWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxnpvut5ja8ghkn9gcs0sqenh2nlk2puqqtnzm8wv2md9w5jhp4sarsr8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTlBmSUhERlNjZjFQdHFG
            S3d6c2JKMlZ5b24yNFN5RnhTdmUybUVzZm00CmJUOU5lYUJwS0RSYTlwbDFrMUdj
            dzZ0UE5LOWsvVk1UVFFLd0ptV21nbFkKLS0tIC9nRVcvVlBvWm5yQlBGQWwvRG5B
            VGtZZ1pCeDFxNlo0UzIyTlhXc0ZvY0EKBqiW6z7wy+2Mjsk5m6/469XCremShVd6
            YjKBkzI2sE+Zi2hwtT97K0uGO35qI05JQ+KDIT6Sx10L+z1rdast+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-19T08:20:28Z"
    mac: ENC[AES256_GCM,data:m6t8C5GPYLtrdhHqxfZhEID/WSb+rwQ9S1uOoyLWJZ0volyY+GIi9dGSlwzwipv5yg8x36jb4epJrMUVjDywvkwVPK+QU2xhzgYEILLTqP9lkaVr4UkN4kuH8P6AUnzkyr8UInKLpS1iDQ50kEVSYk0dCldj6ddBbMSKNqRnnoU=,iv:3//jHH4VFU+ORYZF06qVKQ9jk/YS5a7qSAQCaoG8z58=,tag:sB+coAvbeAY6ut9rfH94yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
