apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:aPkEmFn12w==,iv:jlahmIIspBjUKJ52E/RvGI3Nc3gzECwRp6cokswyZu4=,tag:JccRMQN7CGpsoi95+s7gdQ==,type:str]
    SECRET_NEXTCLOUD_IP: ENC[AES256_GCM,data:CIUytClF/CqD,iv:Yakhb+uXWeHhS5xiI3FdGuOzQulP9KLLH4u2NPsjX8Q=,tag:KaOy7h418JutjBaBzEOypw==,type:str]
    SECRET_JELLYFIN_IP: ENC[AES256_GCM,data:fptbOLIvod6p,iv:tUb6K2Bkp3q1qKKEQR7kC7W3605+SI+C7kBdK9ByXMo=,tag:5O17uQ5aaib6LWX3pau4xg==,type:str]
    SECRET_HOME_ASSISTANT_IP: ENC[AES256_GCM,data:s2Kg6m0WCCS+JQf1IQ==,iv:V5t9KBTg6g9i0GBojQJt32xG9ElJPi8G8vi151ZEims=,tag:JMcp7wXu9JB/SJSbngHTjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxnpvut5ja8ghkn9gcs0sqenh2nlk2puqqtnzm8wv2md9w5jhp4sarsr8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTlBmSUhERlNjZjFQdHFG
            S3d6c2JKMlZ5b24yNFN5RnhTdmUybUVzZm00CmJUOU5lYUJwS0RSYTlwbDFrMUdj
            dzZ0UE5LOWsvVk1UVFFLd0ptV21nbFkKLS0tIC9nRVcvVlBvWm5yQlBGQWwvRG5B
            VGtZZ1pCeDFxNlo0UzIyTlhXc0ZvY0EKBqiW6z7wy+2Mjsk5m6/469XCremShVd6
            YjKBkzI2sE+Zi2hwtT97K0uGO35qI05JQ+KDIT6Sx10L+z1rdast+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T16:17:12Z"
    mac: ENC[AES256_GCM,data:96JNtyiN9AXXHaq0UZ3+P+oP4xsc7yzl0Ug+uXNMPT0XD3DPseLLvRBT1fp/sO4yKbkNmPMCmImhLpa7c+WtT+lj9+A83/1/juRFaF0mr3/iBbFBhmxH9wBI/Vltqe5PO8YfbS+zlyzMsDUUK+cGFv+bNqKDRkbeU2dFpCgqLXk=,iv:vXo4uHJhq7WCagUsCELuwFDYI9OqEoZx1oK+dJW469k=,tag:fABjCSwne9gOLOr7753dHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
