---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: "${SECRET_NAS_HOST}"
    path: /mnt/main/monitoring
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime", "nodiratime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: monitoring
