---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: |-
    - Developer:
      - GitHub:
        - abbr: GH
          href: https://github.com

    - Social:
      - Facebook:
        - abbr: FB
          href: https://facebook.com
      - Threads:
        - abbr: TH
          href: https://threads.net
      - Instagram:
        - abbr: IN
          href: https://instagram.com
      - Twitter:
        - abbr: TW
          href: https://twitter.com

    - Entertainment:
      - YouTube:
        - abbr: YT
          href: https://youtube.com
      - Reddit:
        - abbr: RE
          href: https://reddit.com
  services.yaml: |-
    - Hypervisors:
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: akihabara
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: akihabara
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: shinjuku
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: shinjuku
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: shibuya
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: shibuya
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: nippori
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: nippori
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: ueno
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: ueno
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: kanda
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: kanda
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: yurakucho
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: yurakucho

    - System Admin:
      - Proxmox:
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: Virtual Environment
          icon: /icons/proxmox.png
      - TrueNAS:
          href: http://nas.${SECRET_DOMAIN_INTERNAL}
          description: Network-attached Storage
          icon: /icons/truecommand.png
      - TrueNAS Backup:
          href: http://nas-backup.${SECRET_DOMAIN_INTERNAL}
          description: Network-attached Storage
          icon: /icons/truecommand.png
      - MinIO:
          href: http://minio.${SECRET_DOMAIN_INTERNAL}
          description: Object Storage
          icon: /icons/minio-light.png
      - Grafana:
          href: http://grafana.${SECRET_DOMAIN_INTERNAL}
          description: Monitoring Dashboards
          icon: /icons/grafana.png
      - kube-home Cluster:
          href: http://kubernetes.${SECRET_DOMAIN_INTERNAL}
          description: Kubernetes Dashboard
          icon: /icons/kubernetes-dashboard.png

    - Network Admin:
      - Pi-hole:
          href: https://pihole.${SECRET_DOMAIN_INTERNAL}
          description: DNS Tracker/Ad Blocker
          icon: /icons/pihole.png
      - Omada:
          href: https://omada.${SECRET_DOMAIN_INTERNAL}
          description: AP Management
          icon: /icons/tplink.png
      - Pharos Control:
          href: https://pharos.${SECRET_DOMAIN_INTERNAL}
          description: CPE Management
          icon: /icons/tplink.png
      - FreePBX:
          href: https://voip.${SECRET_DOMAIN_INTERNAL}
          description: VoIP Server
          icon: /icons/freepbx.png

    - Apps:
      - Nextcloud:
          href: https://cloud.${SECRET_DOMAIN}
          description: Personal Private Cloud
          icon: /icons/nextcloud.png
      - Mastodon:
          href: https://mastodon.${SECRET_DOMAIN}
          description: Microblogging Platform
          icon: /icons/mastodon.png
      - Vaultwarden:
          href: https://vault.${SECRET_DOMAIN}
          description: Secrets Manager
          icon: /icons/vaultwarden.png
      - Agent DVR:
          href: https://cctv.${SECRET_DOMAIN_INTERNAL}
          description: Surveillance Monitoring
          icon: /icons/ispy.png
      - Firefly:
          href: https://firefly.${SECRET_DOMAIN_INTERNAL}
          description: Personal Finance
          icon: /icons/firefly.png
      - scanservjs:
          href: https://scanner.${SECRET_DOMAIN_INTERNAL}
          description: Scanner
          icon: /icons/scanservjs.png

    - Media Center:
      - Radarr:
          href: https://radarr.${SECRET_DOMAIN_INTERNAL}
          description: Movie Media Manager
          icon: /icons/radarr.png
      - Sonarr:
          href: https://sonarr.${SECRET_DOMAIN_INTERNAL}
          description: TV Media Manager
          icon: /icons/sonarr.png
      - Prowlarr:
          href: https://prowlarr.${SECRET_DOMAIN_INTERNAL}
          description: Indexer Aggregator
          icon: /icons/prowlarr.png
      - Bazarr:
          href: https://bazarr.${SECRET_DOMAIN_INTERNAL}
          description: Subtitle Manager
          icon: /icons/bazarr.png
      - SABnzbd:
          href: https://sabnzbd.${SECRET_DOMAIN_INTERNAL}
          description: Usenet Newsreader
          icon: /icons/sabnzbd.png
      - qBittorrent:
          href: https://torrents.${SECRET_DOMAIN_INTERNAL}
          description: BitTorrent Client
          icon: /icons/qbittorrent.png
  settings.yaml: |-
    target: _self
    theme: dark
    color: neutral
    layout:
      Hypervisors:
        header: true
        style: row
        columns: 4
  widgets.yaml: |-
    - resources:
        cpu: true
        memory: true
        disk: /

    - search:
        provider: google
        target: _self

    - openweathermap:
        latitude: {{HOMEPAGE_VAR_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_LONGITUDE}}
        units: metric
        apiKey: {{HOMEPAGE_VAR_OPENWEATHERMAP_KEY}}
        cache: 5
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster