---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: |-
    - Developer:
      - GitHub:
        - abbr: GH
          href: https://github.com

    - Social:
      - Facebook:
        - abbr: FB
          href: https://facebook.com
      - Threads:
        - abbr: TH
          href: https://threads.net
      - Instagram:
        - abbr: IN
          href: https://instagram.com
      - Twitter:
        - abbr: TW
          href: https://twitter.com

    - Entertainment:
      - YouTube:
        - abbr: YT
          href: https://youtube.com
      - Reddit:
        - abbr: RE
          href: https://reddit.com
  services.yaml: |-
    - Hypervisors:
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: akihabara
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: akihabara
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: shinjuku
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: shinjuku
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: shibuya
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: shibuya
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: nippori
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: nippori
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: ueno
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: ueno
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: kanda
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: kanda
      - Proxmox:
          icon: /icons/proxmox.png
          href: https://proxmox.${SECRET_DOMAIN_INTERNAL}
          description: yurakucho
          widget:
            type: proxmox
            url: https://proxmox.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: yurakucho

    - System Admin:
      - TrueNAS:
          href: https://nas.${SECRET_DOMAIN_INTERNAL}
          description: Network-Attached Storage
          icon: /icons/truecommand.png
          widget:
            type: truenas
            url: https://nas.${SECRET_DOMAIN_INTERNAL}
            key: {{HOMEPAGE_VAR_NAS_KEY}}
      - TrueNAS Backup:
          href: https://nas-backup.${SECRET_DOMAIN_INTERNAL}
          description: Backup Storage
          icon: /icons/truecommand.png
      - MinIO:
          href: http://minio.${SECRET_DOMAIN_INTERNAL}
          description: Object Storage
          icon: /icons/minio-light.png
      - Grafana:
          href: http://grafana.${SECRET_DOMAIN_INTERNAL}
          description: Monitoring Dashboards
          icon: /icons/grafana.png
      - kube-home Cluster:
          href: http://kubernetes.${SECRET_DOMAIN_INTERNAL}
          description: Kubernetes Dashboard
          icon: /icons/kubernetes-dashboard.png

    - Network Admin:
      - Pi-hole:
          href: https://pihole.${SECRET_DOMAIN_INTERNAL}
          description: DNS Tracker/Ad Blocker
          icon: /icons/pihole.png
          widget:
            type: pihole
            url: https://pihole.${SECRET_DOMAIN_INTERNAL}
            key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
      - Omada (Home):
          href: https://omada.${SECRET_DOMAIN_INTERNAL}
          description: SDN Management
          icon: /icons/tplink.png
          widget:
            type: omada
            url: https://omada-controller.default.svc.cluster.local
            username: {{HOMEPAGE_VAR_OMADA_USERNAME}}
            password: {{HOMEPAGE_VAR_OMADA_PASSWORD}}
            site: HDC
            fields: ["connectedAp", "activeUser", "alerts"]
      - Omada (Haven):
          href: https://omada.${SECRET_DOMAIN_INTERNAL}
          description: SDN Management
          icon: /icons/tplink.png
          widget:
            type: omada
            url: https://omada-controller.default.svc.cluster.local
            username: {{HOMEPAGE_VAR_OMADA_USERNAME}}
            password: {{HOMEPAGE_VAR_OMADA_PASSWORD}}
            site: School
            fields: ["connectedAp", "activeUser", "alerts"]
      - Pharos Control:
          href: https://pharos.${SECRET_DOMAIN_INTERNAL}
          description: CPE Management
          icon: /icons/tplink.png
      - FreePBX:
          href: https://voip.${SECRET_DOMAIN_INTERNAL}
          description: VoIP Server
          icon: /icons/freepbx.png

    - Apps:
      - Nextcloud:
          href: https://cloud.${SECRET_DOMAIN}
          description: Personal Private Cloud
          icon: /icons/nextcloud.png
          widget:
            type: nextcloud
            url: https://cloud.${SECRET_DOMAIN}
            key: {{HOMEPAGE_VAR_NEXTCLOUD_KEY}}
            fields: ["freespace", "activeusers", "numfiles"]
      - Mastodon:
          href: https://mastodon.${SECRET_DOMAIN}
          description: Microblogging Platform
          icon: /icons/mastodon.png
          widget:
            type: mastodon
            url: https://mastodon.${SECRET_DOMAIN}
      - Home Assistant:
          href: https://home.${SECRET_DOMAIN}
          description: Smart Home Automation
          icon: /icons/homeassistant.png
          widget:
            type: homeassistant
            url: https://home.${SECRET_DOMAIN}
            key: {{HOMEPAGE_VAR_HOME_ASSISTANT_KEY}}
      - Vaultwarden:
          href: https://vault.${SECRET_DOMAIN}
          description: Secrets Manager
          icon: /icons/vaultwarden.png
      - Agent DVR:
          href: https://cctv.${SECRET_DOMAIN_INTERNAL}
          description: Surveillance Monitoring
          icon: /icons/ispy.png
      - Firefly:
          href: https://firefly.${SECRET_DOMAIN_INTERNAL}
          description: Personal Finance
          icon: /icons/firefly.png
      - scanservjs:
          href: https://scanner.${SECRET_DOMAIN_INTERNAL}
          description: Scanner
          icon: /icons/scanservjs.png

    - Media Center:
      - Jellyfin:
          href: https://jellyfin.${SECRET_DOMAIN}
          description: Media Server
          icon: /icons/jellyfin.png
          widget:
            type: jellyfin
            url: http://jellyfin.media.svc.cluster.local:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
      - Radarr:
          href: https://radarr.${SECRET_DOMAIN_INTERNAL}
          description: Movie Media Manager
          icon: /icons/radarr.png
          widget:
            type: radarr
            url: http://radarr.media.svc.cluster.local:7878
            key: {{HOMEPAGE_VAR_RADARR_KEY}}
      - Sonarr:
          href: https://sonarr.${SECRET_DOMAIN_INTERNAL}
          description: TV Media Manager
          icon: /icons/sonarr.png
          widget:
            type: sonarr
            url: http://sonarr.media.svc.cluster.local:8989
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
      - Prowlarr:
          href: https://prowlarr.${SECRET_DOMAIN_INTERNAL}
          description: Indexer Aggregator
          icon: /icons/prowlarr.png
          widget:
            type: prowlarr
            url: http://prowlarr.media.svc.cluster.local:9696
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}
      - Bazarr:
          href: https://bazarr.${SECRET_DOMAIN_INTERNAL}
          description: Subtitle Manager
          icon: /icons/bazarr.png
          widget:
            type: bazarr
            url: http://bazarr.media.svc.cluster.local:6767
            key: {{HOMEPAGE_VAR_BAZARR_KEY}}
      - SABnzbd:
          href: https://sabnzbd.${SECRET_DOMAIN_INTERNAL}
          description: Usenet Newsreader
          icon: /icons/sabnzbd.png
          widget:
            type: sabnzbd
            url: https://sabnzbd.${SECRET_DOMAIN_INTERNAL}
            key: {{HOMEPAGE_VAR_SABNZBD_KEY}}
      - qBittorrent:
          href: https://torrents.${SECRET_DOMAIN_INTERNAL}
          description: BitTorrent Client
          icon: /icons/qbittorrent.png
          widget:
            type: qbittorrent
            url: https://torrents.${SECRET_DOMAIN_INTERNAL}
            username: {{HOMEPAGE_VAR_TORRENTS_USERNAME}}
            password: {{HOMEPAGE_VAR_TORRENTS_PASSWORD}}
  settings.yaml: |-
    target: _self
    theme: dark
    color: slate
    background: 
      image: https://home.${SECRET_DOMAIN}/local/wallpaper.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100
    # cardBlur: sm
    useEqualHeights: true
    layout:
      Hypervisors:
        header: true
        style: row
        columns: 4
      System Admin:
        header: true
        style: row
        columns: 3
      Network Admin:
        header: true
        style: row
        columns: 3
      Apps:
        header: true
        style: row
        columns: 3
      Media Center:
        header: true
        style: row
        columns: 3
  widgets.yaml: |-
    - resources:
        cpu: true
        memory: true
        disk: /

    - search:
        provider: google
        target: _self

    - openweathermap:
        latitude: {{HOMEPAGE_VAR_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_LONGITUDE}}
        units: metric
        apiKey: {{HOMEPAGE_VAR_OPENWEATHERMAP_KEY}}
        cache: 5

    - datetime:
        text_size: xl
        format:
          dateStyle: short
          timeStyle: short
          hour12: true
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster